apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-deployment
spec:
  selector:
    matchLabels:
      app: express-test-deployment
  template:
    metadata:
      labels:
        app: express-test-deployment
    spec:
      containers:
      - name: express-test-deployment
        image: sgse2/express-test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-test-service
spec:
  selector:
    app: express-test-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 30100
